UPDATE contributions SET receipt_date = '2019-05-16' WHERE receipt_date = '1986-05-16';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, 'Chancellors', 'Chancellor''s') WHERE number_and_street LIKE '%Chancellors%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, 'Queen Anne''s', 'Queen Annes') WHERE number_and_street LIKE '%Queen Anne''s%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, 'Buuchanan', 'Buchanan') WHERE number_and_street LIKE '%Buuchanan%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, 'N.W', 'NW') WHERE number_and_street LIKE '%N.W%';
UPDATE contributions SET number_and_street = number_and_street || ' NW' WHERE number_and_street LIKE '% Western Ave'
    OR number_and_street LIKE ' New Hampshire Ave' OR number_and_street LIKE '% Garfield Terrace' OR number_and_street LIKE '% Chevy Chase Parkway';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, 'New Mexico Ane', 'New Mexico Ave') WHERE number_and_street LIKE '%New Mexico Ane%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Sst ', ' St ') WHERE number_and_street LIKE '% Sst %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' N Gate ', ' Northgate ') WHERE number_and_street LIKE '% N Gate %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Rock Creek R', ' Rock Creek Church R') WHERE number_and_street LIKE '% Rock Creek R%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Rhode lsland ', ' Rhode Island ') WHERE number_and_street LIKE '% Rhode lsland %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Masschusetts ', ' Massachusetts ') WHERE number_and_street LIKE '% Masschusetts %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Farragust ', ' Farragut ') WHERE number_and_street LIKE '% Farragust %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Pleasnat ', ' Pleasant ') WHERE number_and_street LIKE '% Pleasnat %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Randolf ', ' Randolph ') WHERE number_and_street LIKE '% Randolf %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Varumn ', ' Varnum ') WHERE number_and_street LIKE '% Varumn %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' AspenSt ', ' Aspen St ') WHERE number_and_street LIKE '% AspenSt %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Piney Brand ', ' Piney Branch ') WHERE number_and_street LIKE '% Piney Brand %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Deer Xing', ' Deer Crossing') WHERE number_and_street LIKE '% Deer Xing%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Upshur Ave ', ' Upshur St ') WHERE number_and_street LIKE '% Upshur Ave %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Monroe Ave ', ' Monroe St ') WHERE number_and_street LIKE '% Monroe Ave %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Leegate Rd', ' Leegate Rd NW') WHERE number_and_street LIKE '% Leegate Rd';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Montana Ave', ' Montana Ave NE') WHERE number_and_street LIKE '% Montana Ave';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Kilbourne', ' Kilbourne Pl NW') WHERE number_and_street LIKE '% Kilbourne';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Arkansas', ' Arkansas Ave NW') WHERE number_and_street LIKE '% Arkansas';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Warder St', ' Warder St NW') WHERE number_and_street LIKE '% Warder St';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Acker Pl', ' Acker Pl NE') WHERE number_and_street LIKE '% Acker Pl';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Flagler', ' Flagler Pl NW') WHERE number_and_street LIKE '% Flagler';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Bunker Hill Rd', ' Bunker Hill Rd NE') WHERE number_and_street LIKE '% Bunker Hill Rd';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Bunker Hil ', ' Bunker Hill ') WHERE number_and_street LIKE '% Bunker Hil %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Douglass Pl', ' Douglas Pl') WHERE number_and_street LIKE '% Douglass Pl%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Maryland Ave #', ' Maryland Ave NW #') WHERE number_and_street LIKE '% Maryland Ave #%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' MacArthur Blvds. #', ' MacArthur Blvd NW #') WHERE number_and_street LIKE '% MacArthur Blvds. #%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Connecticut Ave 1', ' Connecticut Ave NW 1') WHERE number_and_street LIKE '% Connecticut Ave 1%';
UPDATE contributions SET number_and_street = '3293 Worthington St NW' WHERE number_and_street = '6293 Worthington St NW';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Lawrence NE', ' Lawrence St NE') WHERE number_and_street LIKE '% Lawrence NE%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Martin Luther King Jr SE', ' Martin Luther King Jr Ave SE')
    WHERE number_and_street LIKE '% Martin Luther King Jr SE%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' NW#', ' NW #') WHERE number_and_street LIKE '% NW#%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' 21st nw', ' 21st St NW') WHERE number_and_street LIKE '% 21st nw%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' 13th NW', ' 13th St NW') WHERE number_and_street LIKE '% 13th NW%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' M NW', ' M St NW') WHERE number_and_street LIKE '% M NW%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' 8th NE', ' 8th St NE') WHERE number_and_street LIKE '% 8th NE%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' A NE', ' A St NE') WHERE number_and_street LIKE '% A NE%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' 3rd NE', ' 8th St NE') WHERE number_and_street LIKE '% 3rd NE%';
UPDATE contributions SET number_and_street = '1301 M Street NW, Apt. 1003' WHERE number_and_street = '1301 M Street, Apt. 1003';
UPDATE contributions SET number_and_street = number_and_street || ' NE' WHERE number_and_street = '653 Anacostia Avenue';
UPDATE contributions SET number_and_street = '1301 SOUTH CAROLINA AVENUE SE' WHERE number_and_street = '1301 SOUTH CAROLINA AVENUE ...';
UPDATE contributions SET number_and_street = '1120 Rhode Island Avenue NW' WHERE number_and_street = '1120 Rhode Island Avenue, N...';
UPDATE contributions SET number_and_street = '3612 Austin St SE' WHERE number_and_street LIKE '3612 Austin%' AND contributor_last_name = 'Capozzi';
UPDATE contributions SET number_and_street = '3309 4th St SE' WHERE number_and_street = '3309 4th St SW' AND contributor_last_name = 'Batchelor';
UPDATE contributions SET contributor_middle_name = 'Mitchell' WHERE number_and_street LIKE '910 M St%' AND contributor_last_name = 'Grossman' AND contributor_first_name = 'Jordan';
UPDATE contributions SET contributor_middle_name = 'Brinn' WHERE number_and_street LIKE '7026 Longwood%' AND contributor_last_name = 'Siegel' AND contributor_first_name = 'Susan';
UPDATE contributions SET contributor_middle_name = 'Levin' WHERE number_and_street LIKE '715 6th%' AND contributor_last_name = 'Welan' AND contributor_first_name = 'Joy';
UPDATE contributions SET contributor_middle_name = 'L' WHERE number_and_street LIKE '916 Spruce%' AND contributor_last_name = 'Benjamin' AND contributor_first_name = 'Michael';
UPDATE contributions SET contributor_last_name = 'Teutsch' WHERE contributor_last_name = 'Teutsh';

INSERT OR IGNORE INTO committee_extras SELECT committee_name, NULL FROM committees;
UPDATE committee_extras SET last_report_date = '2019-07-31';
UPDATE committee_extras SET last_report_date = '2019-08-31' where committee_name LIKE '%Lewis George%';
