UPDATE contributions SET receipt_date = '2019-05-16' WHERE receipt_date = '1986-05-16';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, 'Chancellors', 'Chancellor''s') WHERE number_and_street LIKE '%Chancellors%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, 'Queen Anne''s', 'Queen Annes') WHERE number_and_street LIKE '%Queen Anne''s%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, 'Buuchanan', 'Buchanan') WHERE number_and_street LIKE '%Buuchanan%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, 'N.W', 'NW') WHERE number_and_street LIKE '%N.W%';
UPDATE contributions SET number_and_street = number_and_street || ' NW' WHERE number_and_street LIKE '% Western Ave'
    OR number_and_street LIKE ' New Hampshire Ave' OR number_and_street LIKE '% Garfield Terrace' OR number_and_street LIKE '% Chevy Chase Parkway';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, 'New Mexico Ane', 'New Mexico Ave') WHERE number_and_street LIKE '%New Mexico Ane%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Sst ', ' St ') WHERE number_and_street LIKE '% Sst %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' N Gate ', ' Northgate ') WHERE number_and_street LIKE '% N Gate %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Rock Creek R', ' Rock Creek Church R') WHERE number_and_street LIKE '% Rock Creek R%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Rhode lsland ', ' Rhode Island ') WHERE number_and_street LIKE '% Rhode Island %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Masschusetts ', ' Massachusetts ') WHERE number_and_street LIKE '% Masschusetts %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Farragust ', ' Farragut ') WHERE number_and_street LIKE '% Farragust %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Pleasnat ', ' Pleasant ') WHERE number_and_street LIKE '% Pleasnat %';
UPDATE contributions SET number_and_street = '3293 Worthington St NW' WHERE number_and_street = '6293 Worthington St NW';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' Lawrence NE', ' Lawrence St NE') WHERE number_and_street LIKE '% Lawrence NE%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' NW# ', ' NW #') WHERE number_and_street LIKE '% NW# %';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' 21st nw', ' 21st St NW') WHERE number_and_street LIKE '% 21st nw%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' M NW', ' M St NW') WHERE number_and_street LIKE '% M NW%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' 8th NE', ' 8th St NE') WHERE number_and_street LIKE '% 8th NE%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' A NE', ' A St NE') WHERE number_and_street LIKE '% A NE%';
UPDATE contributions SET number_and_street = REPLACE(number_and_street, ' 3rd NE', ' 8th St NE') WHERE number_and_street LIKE '% 3rd NE%';
UPDATE contributions SET number_and_street = '1301 M Street NW, Apt. 1003' WHERE number_and_street = '1301 M Street, Apt. 1003';
UPDATE contributions SET number_and_street = number_and_street || ' NE' WHERE number_and_street = '653 Anacostia Avenue';
UPDATE contributions SET number_and_street = '1301 SOUTH CAROLINA AVENUE SE' WHERE number_and_street = '1301 SOUTH CAROLINA AVENUE ...';
UPDATE contributions SET number_and_street = '1120 Rhode Island Avenue NW' WHERE number_and_street = '1120 Rhode Island Avenue, N...';
UPDATE contributions SET number_and_street = '3612 Austin St SE' WHERE number_and_street LIKE '3612 Austin%' AND contributor_last_name = 'Capozzi';
